import Joi from 'joi';
import { Order } from './orderInterface';

const additionalFeaturesSchema = Joi.object({
  handheldRemote: Joi.string().optional().allow('', null),
  motionSensor: Joi.string().optional().allow('', null),
  ledLight: Joi.string().optional().allow('', null),
  smartHub: Joi.string().optional().allow('', null),
  variValance: Joi.string().optional().allow('', null),
  variPitch: Joi.string().optional().allow('', null),
  hood: Joi.string().optional().allow('', null),
  crankHandleLength: Joi.string().optional().allow('', null),
  customRoofBracket: Joi.string().optional().allow('', null),
  quantity: Joi.number().optional().allow(null),
  furring_ft: Joi.number().optional().allow(null),
  spacers_ft: Joi.number().optional().allow(null),
  wedges: Joi.number().optional().allow(null),
  conduit: Joi.number().optional().allow(null),
  additionalCost: Joi.string().optional().allow('', null),
  additionalCostAmount: Joi.number().optional().allow(null),
  instructions: Joi.string().optional().allow('', null),
  ceilingLights: Joi.string().optional().allow('', null),
  ceilingFanBeam: Joi.string().optional().allow('', null),
  ceilingFanInstall: Joi.string().optional().allow('', null),
  steelForPost: Joi.string().optional().allow('', null),
  steelForHeader: Joi.string().optional().allow('', null),
  footings: Joi.string().optional().allow('', null),
  rafterCut: Joi.string().optional().allow('', null),
  doubleRaterBeams: Joi.string().optional().allow('', null),
  doubleHeaderBeams: Joi.string().optional().allow('', null),
  powerOutlet: Joi.string().optional().allow('', null),
  custom: Joi.string().optional().allow('', null),
});

const locationSchema = Joi.object({
  latitude: Joi.number().required(),
  longitude: Joi.number().required(),
  address: Joi.string().required(),
});

export const OrderValidator = {
  create: Joi.object<Order>({
    quoteId: Joi.string().required(),
    awningType: Joi.string().required(),
    product: Joi.string().required(),
    custom: Joi.string().optional().allow('', null),
    operation: Joi.string().optional().allow('', null),
    productName: Joi.string().optional().allow('', null),
    hardwareColor: Joi.string().optional().allow('', null),
    roofColor: Joi.string().optional().allow('', null),
    bays: Joi.string().optional().allow('', null),
    unitSize: Joi.string().optional().allow('', null),
    width_ft: Joi.number().optional().allow(null),
    width_in: Joi.number().optional().allow(null),
    widthFraction: Joi.string().optional().allow('', null),
    height_ft: Joi.number().optional().allow(null),
    height_in: Joi.number().optional().allow(null),
    heightFraction: Joi.string().optional().allow('', null),
    projection_ft: Joi.number().optional().allow(null),
    projection_in: Joi.number().optional().allow(null),
    projectionFraction: Joi.string().optional().allow('', null),
    projection: Joi.string().optional().allow('', null),
    picketSize: Joi.string().optional().allow('', null),
    picketSpacing: Joi.string().optional().allow('', null),
    crank: Joi.string().optional().allow('', null),
    motorized: Joi.string().optional().allow('', null),
    fabric: Joi.string().optional().allow('', null),
    fabricTab: Joi.string().optional().allow('', null),
    magnetLatch: Joi.string().optional().allow('', null),
    quantity: Joi.number().optional().allow(null),
    valancaHeight: Joi.string().optional().allow('', null),
    valancaStyle: Joi.string().optional().allow('', null),
    bindingColor: Joi.string().optional().allow('', null),
    installation: Joi.string().optional().allow('', null),
    story: Joi.string().optional().allow('', null),
    description: Joi.string().optional().allow('', null),
    frameUpgrade: Joi.string().optional().allow('', null),
    frameUpgradePercentage: Joi.string().optional().allow('', null),
    post2: Joi.string().optional().allow('', null),
    post2Percentage: Joi.string().optional().allow('', null),
    post3: Joi.string().optional().allow('', null),
    post3Percentage: Joi.string().optional().allow('', null),
    post4: Joi.string().optional().allow('', null),
    post4Percentage: Joi.string().optional().allow('', null),
    unitPrice: Joi.number().optional().allow(null),
    location: locationSchema.optional(),
    additionalFeatures: additionalFeaturesSchema.optional(),
    createdBy: Joi.string().optional(),
  }),

  update: Joi.object<Partial<Order>>({
    quoteId: Joi.string().optional(),
    awningType: Joi.string().optional(),
    product: Joi.string().optional(),
    custom: Joi.string().optional().allow('', null),
    operation: Joi.string().optional().allow('', null),
    productName: Joi.string().optional().allow('', null),
    hardwareColor: Joi.string().optional().allow('', null),
    roofColor: Joi.string().optional().allow('', null),
    bays: Joi.string().optional().allow('', null),
    unitSize: Joi.string().optional().allow('', null),
    width_ft: Joi.number().optional().allow(null),
    width_in: Joi.number().optional().allow(null),
    widthFraction: Joi.string().optional().allow('', null),
    height_ft: Joi.number().optional().allow(null),
    height_in: Joi.number().optional().allow(null),
    heightFraction: Joi.string().optional().allow('', null),
    projection_ft: Joi.number().optional().allow(null),
    projection_in: Joi.number().optional().allow(null),
    projectionFraction: Joi.string().optional().allow('', null),
    projection: Joi.string().optional().allow('', null),
    picketSize: Joi.string().optional().allow('', null),
    picketSpacing: Joi.string().optional().allow('', null),
    crank: Joi.string().optional().allow('', null),
    motorized: Joi.string().optional().allow('', null),
    fabric: Joi.string().optional().allow('', null),
    fabricTab: Joi.string().optional().allow('', null),
    magnetLatch: Joi.string().optional().allow('', null),
    quantity: Joi.number().optional().allow(null),
    valancaHeight: Joi.string().optional().allow('', null),
    valancaStyle: Joi.string().optional().allow('', null),
    bindingColor: Joi.string().optional().allow('', null),
    installation: Joi.string().optional().allow('', null),
    story: Joi.string().optional().allow('', null),
    description: Joi.string().optional().allow('', null),
    frameUpgrade: Joi.string().optional().allow('', null),
    frameUpgradePercentage: Joi.string().optional().allow('', null),
    post2: Joi.string().optional().allow('', null),
    post2Percentage: Joi.string().optional().allow('', null),
    post3: Joi.string().optional().allow('', null),
    post3Percentage: Joi.string().optional().allow('', null),
    post4: Joi.string().optional().allow('', null),
    post4Percentage: Joi.string().optional().allow('', null),
    unitPrice: Joi.number().optional().allow(null),
    location: locationSchema.optional(),
    additionalFeatures: additionalFeaturesSchema.optional(),
  }), 

  getAll: Joi.object({
    paginate: Joi.boolean().default(true),
    page: Joi.number().min(1).default(1),
    perPage: Joi.number().min(1).max(100).default(10),
    search: Joi.string().optional().allow(''),
    quoteId: Joi.string().optional(),
  }),
};
